name: Manual Cypress Tests
on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Tests to be included with priority level: smoke,basic,coverage'
        required: true
        default: 'smoke'
      app:
        description: 'Application under test: careesma, engineerjobs, wowjobs, gigajob, workopolis'
        required: true
        default: 'careesma'
      stage:
        description: 'Stage: qa, prod'
        required: true
        default: 'qa'
      browser:
        description: 'Browser: chrome, firefox, edge'
        required: true
        default: 'chrome'
      platform:
        description: 'Platform: desktop, mobile'
        required: true
        default: '["desktop"]'
      reportToDashboard:
        description: 'Do you want to results to Dashboard: true, false'
        required: true
        default: true


jobs:
  test-workflow:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Cypress tests
        uses: cypress-io/github-action@v3
        with:
          env: scope=${{ github.event.inputs.scope }},app=${{ github.event.inputs.app }},stage=${{ github.event.inputs.stage }},executionPlatforms=${{ github.event.inputs.platform }}
          spec:
            cond: $(git diff --name-only origin/main -- cypress/e2e)
          browser: ${{ github.event.inputs.browser }}
          tag: '${{ github.event.inputs.app }},${{ github.event.inputs.stage }},${{ github.event.inputs.browser }},${{ github.event.inputs.platform }}'
          record: ${{ github.event.inputs.reportToDashboard }}
        env:
          CORTEX_GITHUB_TOKEN_NPM: ${{ secrets.PUBLISH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          PUBLISH_TOKEN_NPM: ${{ secrets.PUBLISH_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESSDASHBOARDFORCLIENTSITES }}
